### ISSUE TITLE
Try XFOIL for low Re 0018 data

### ISSUE THREAD

**Issue by petebachant** [petebachant/RM2-CACTUS#38]
Though the results at `Re = 1.5e6` show XFOIL to do a poor job for the 0021, if it does better than Sheldahl at matching the Jacobs data for the 0018, there may be some justification for its use for generating low Re 0021 coefficients.

**Comment by nearyvs** [comment]
Why are we comparing with 0018 foil Jacobs?

**Comment by petebachant** [comment]
Since I can't find any 0021 data at the Reynolds numbers of interest (~1e5), and XFOIL has already failed in the stalled regime at Re ~ 1e6, the thought was that we could validate against a profile that is kind of similar. It's probably going to fail just the same, but it was just a thought.

**Comment by petebachant** [comment]
Actually, there is lift coefficient data in Jacobs (1932), which I'm going to manually digitize and compare with Sheldahl.

**Comment by petebachant** [comment]
Going to close this and generate some XFOIL data at low Re for the 0021.
