### ISSUE TITLE
Add walls

### ISSUE THREAD

**Issue by petebachant** [petebachant/RM2-CACTUS#9]
Will need some advice from @whophil on this one!

**Comment by petebachant** [comment]
See https://gist.github.com/whophil/e5405071a143b38aa4d64dbcd4acef3a

**Comment by petebachant** [comment]
Making some good progress on this on the `walls` branch. Not sure if CACTUS uses a y-up coordinate system though...

**Comment by whophil** [comment]
Yep, +y up.

**Comment by petebachant** [comment]
Great, thanks Phil! The walls seem to be working well. Loading is just a little higher than with just the ground plane.
